[package]
name = "cdk-user"
version = "0.1.0"
edition = "2021"
description = "User-space runtime and programs for CDK (packed into the boot ramdisk)"
license = "Apache-2.0"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
cdk-ml = { path = "ml" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "s"
debug = false
